# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
# - name: Airflow Webserver | Ensure airflow is configured
#   import_role:
#     name: tosit.tdp_extra.airflow.common
#     tasks_from: config

- name: Airflow | Copy webserver_config.py file
  template:
    src: webserver_config.py.j2
    dest: "{{ airflow_install_dir }}/webserver_config.py"

- name: Airflow | Copy webserver service file
  template:
    src: airflow-webserver.service.j2
    dest: /usr/lib/systemd/system/airflow-webserver.service