# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
# - name: Airflow Webserver | Ensure airflow is configured
#   import_role:
#     name: tosit.tdp_extra.airflow.common
#     tasks_from: config

- name: Airflow | Copy webserver service file
  template:
    src: airflow-webserver.service.j2
    dest: /usr/lib/systemd/system/airflow-webserver.service

- name: Airflow | Database Init
  shell: "{{ airflow_executable }} db init"
  environment:
    AIRFLOW_HOME: "{{ airflow_install_dir }}"

- name: Airflow | Create admin user
  shell: |
    "{{ airflow_executable }}" users create \
      --username {{ airflow_admin_user }} \
      --password {{ airflow_admin_pass }} \
      --role Admin \
      --firstname admin \
      --lastname admin \
      --email admin@tdp
  environment:
    AIRFLOW_HOME: "{{ airflow_install_dir }}"

- name: Airflow | Delete hive connection '{{ hive.conn_id }}' if exists
  shell: "{{ airflow_executable }} connections delete {{ hive.conn_id }}"
  environment:
    AIRFLOW_HOME: "{{ airflow_install_dir }}"
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  ignore_errors: true

- name: Airflow | Add hive connection '{{ hive.conn_id }}'
  shell: |
    "{{ airflow_executable }}" connections add {{ hive.conn_id }} \
      --conn-type {{ hive.conn_type }} \
      --conn-host {{ hive.host }} \
      --conn-schema {{ hive.schema }} \
      --conn-port {{ hive.port }} \
      --conn-extra '{"use_beeline": "{{ hive.use_beeline }}", "proxy_user": "{{ hive.proxy_user }}", "principal": "{{ hive.principal }}"}'
  environment:
    AIRFLOW_HOME: "{{ airflow_install_dir }}"
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"

- name: Airflow | Delete spark3 connection '{{ spark3.conn_id }}' if exists
  shell: "{{ airflow_executable }} connections delete {{ spark3.conn_id }}"
  environment:
    AIRFLOW_HOME: "{{ airflow_install_dir }}"
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  ignore_errors: true

- name: Airflow | Add spark3 connection '{{ spark3.conn_id }}'
  shell: |
    "{{ airflow_executable }}" connections add {{ spark3.conn_id }} \
      --conn-type {{ spark3.conn_type }} \
      --conn-host {{ spark3.host }} \
      --conn-extra '{"proxy_user": "{{ spark3.proxy_user }}"}'
  environment:
    AIRFLOW_HOME: "{{ airflow_install_dir }}"
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"