# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
# - name: Airflow Webserver | Ensure airflow is installed
#   import_role:
#     name: tosit.tdp_extra.airflow.common
#     tasks_from: install