# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
- name: Airflow | Restart airflow-webserver service
  systemd:
    name: airflow-webserver
    state: restarted
    enabled: true
    daemon_reload: true