# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
- name: Airflow | Start airflow-worker service
  systemd:
    name: airflow-worker
    state: restarted
    enabled: true
    daemon_reload: true

- name: Airflow | Start airflow-flower service
  systemd:
    name: airflow-flower
    state: restarted
    enabled: true
    daemon_reload: true