---
- name: Airflow | Add airflow group
  group:
    name: "{{ airflow_group }}"

- name: Airflow | Add airflow user
  user:
    name: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Ensures {{ airflow_root_dir }} exists
  file:
    path: "{{ airflow_root_dir }}/airflow-{{ airflow_version }}"
    state: directory
    owner: root
    group: root
    mode: "755"

- name: Airflow | Create symbolic link to Airflow installation
  file:
    src: "{{ airflow_root_dir }}/airflow-{{ airflow_version }}"
    dest: "{{ airflow_install_dir }}"
    state: link
  
- name: Airflow | Copy constraints file
  template:
    src: constraints-3.6.txt.j2
    dest: /tmp/constraints-3.6.txt

- name: Airflow | Install Python dependencies
  pip:
    name: "{{ airflow_required_python_packages }}"
    executable: pip3
  when: airflow_required_python_packages is defined

- name: Airflow | Pip install airflow {{ airflow_version }}
  pip:
    name: "apache-airflow=={{ airflow_version }}"
    executable: pip3
    extra_args: --constraint /tmp/constraints-3.6.txt

- name: Airflow | Install Required packages
  yum:
    pkg: "{{ airflow_required_packages }}"
    state: present

# - name: Airflow | Pip install celery 
#   become: true
#   become_user: "{{ airflow_user }}"
#   pip:
#     name: "celery"
#     executable: pip3
#     extra_args: --constraint /tmp/constraints-3.6.txt

# - name: Airflow | Pip install redis
#   become: true
#   become_user: "{{ airflow_user }}"
#   pip:
#     name: "redis"
#     executable: pip3
#     extra_args: --constraint /tmp/constraints-3.6.txt