# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Airflow | Add airflow group
  group:
    name: "{{ airflow_group }}"

- name: Airflow | Add airflow user
  user:
    name: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Airfloww | Ensures airflow install, certificates and configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ airflow_root_dir }}/airflow-{{ airflow_version }}"
    - "{{ airflow_certs_dir }}"
    - "{{ airflow_root_conf_dir }}"

- name: Airflow | Create symbolic link to Airflow installation
  file:
    src: "{{ airflow_root_dir }}/airflow-{{ airflow_version }}"
    dest: "{{ airflow_install_dir }}"
    state: link
  
- name: Airflow | Copy constraints file
  template:
    src: constraints-3.6.txt.j2
    dest: /tmp/constraints-3.6.txt

- name: Airflow | Install Python dependencies
  pip:
    name: "{{ airflow_required_python_packages }}"
    executable: pip3
  when: airflow_required_python_packages is defined

- name: Airflow | Pip install airflow {{ airflow_version }}
  pip:
    name: "apache-airflow[celery]=={{ airflow_version }}"
    executable: pip3
    extra_args: --constraint /tmp/constraints-3.6.txt

- name: Airflow | Install Required packages
  yum:
    pkg: "{{ airflow_required_packages }}"
    state: present

- name: Airflow | Pip install flower
  pip:
    name: flower
    executable: pip3
    extra_args: --constraint /tmp/constraints-3.6.txt