# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Ensure kerberos common installation steps are performed
  import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: install

- name: Ensure airflow user's principal and keytab exist
  import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: create_principal_keytab
  vars:
    principal: airflow/{{ ansible_fqdn }}
    keytab: airflow.service.keytab
    user: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: "0600"
  when: krb_create_principals_keytabs

- name: Ensure airflow's keytab is working
  import_role:
    name: tosit.tdp.utils.kerberos
    tasks_from: check_secure_keytab
  vars:
    principal: airflow/{{ ansible_fqdn }}
    keytab: airflow.service.keytab
    user: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: "640"
  when: not krb_create_principals_keytabs