# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
# Install airflow
- import_playbook: ../airflow_install.yml
- import_playbook: ../airflow_ssl-tls.yml
- import_playbook: ../airflow_config.yml

# Webserver
- import_playbook: ../airflow_webserver_install.yml
- import_playbook: ../airflow_webserver_config.yml