# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
# Install airflow
- import_playbook: ../airflow_webserver_install.yml
- import_playbook: ../airflow_scheduler_install.yml
- import_playbook: ../airflow_worker_install.yml

# configure airflow
- import_playbook: ../airflow_webserver_config.yml
- import_playbook: ../airflow_scheduler_config.yml
- import_playbook: ../airflow_worker_config.yml

# Secure airflow with SSL/TLS
- import_playbook: ../airflow_sst-tls_install.yml

# kerberize airflow
- import_playbook: ../airflow_kerberos_install.yml

# Upload DAG files
- import_playbook: ../airflow_upload-dags.yml

# Restart airflow services
- import_playbook: ../airflow_webserver_restart.yml
- import_playbook: ../airflow_worker_restart.yml
- import_playbook: ../airflow_scheduler_restart.yml